#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

static std::string read_file(fs::path const &path) {
    std::ifstream f(path, std::ios::binary);
    if (!f) {
        std::cerr << "po2cpp: cannot open " << path << "\n";
        std::exit(1);
    }
    std::ostringstream ss;
    ss << f.rdbuf();
    return ss.str();
}

static std::string pick_delimiter(std::string_view content) {
    std::string delim = "PO";
    while (content.find(")" + delim + "\"") != std::string_view::npos)
        delim += "=";
    return delim;
}

static std::string stem_to_identifier(std::string const &stem) {
    std::string id;
    for (char c : stem)
        id += (std::isalnum(static_cast<unsigned char>(c)) ? c : '_');
    return id;
}

static void usage() {
    std::cerr << "Usage: po2cpp -o <output.cpp> <lang1.po> [lang2.po ...]\n"
              << "\n"
              << "Generates a .cpp implementing i18n::builtin::get() and\n"
              << "i18n::builtin::languages() with embedded .po data.\n"
              << "Include <i18n/builtin.hpp> for the declarations.\n";
    std::exit(1);
}

int main(int argc, char *argv[]) {
    std::string output;
    std::vector<std::string> inputs;

    for (int i = 1; i < argc; ++i) {
        std::string arg = argv[i];
        if (arg == "-o" && i + 1 < argc) {
            output = argv[++i];
        } else if (arg == "-h" || arg == "--help") {
            usage();
        } else {
            inputs.push_back(arg);
        }
    }
    if (output.empty() || inputs.empty()) usage();

    struct Lang {
        std::string code;
        std::string ident;
        std::string content;
        std::string delim;
    };
    std::vector<Lang> langs;

    for (auto const &path : inputs) {
        auto stem = fs::path(path).stem().string();
        auto content = read_file(path);
        langs.push_back({stem, stem_to_identifier(stem), content,
                         pick_delimiter(content)});
    }

    std::ofstream out(output);
    if (!out) {
        std::cerr << "po2cpp: cannot write " << output << "\n";
        return 1;
    }

    out << "// Generated by po2cpp — do not edit\n";
    out << "#include \"i18n/builtin.hpp\"\n\n";
    out << "#include <array>\n";
    out << "#include <string_view>\n\n";
    out << "namespace i18n::builtin {\n\n";

    for (auto const &l : langs) {
        out << "static constexpr char " << l.ident << "_data[] = R\""
            << l.delim << "(" << l.content << ")" << l.delim << "\";\n\n";
    }

    out << "struct LangEntry { std::string_view code; std::string_view data; };\n\n";
    out << "static constexpr std::array<LangEntry, " << langs.size()
        << "> entries = {{\n";
    for (size_t i = 0; i < langs.size(); ++i) {
        out << "    {\"" << langs[i].code << "\", " << langs[i].ident
            << "_data}";
        if (i + 1 < langs.size()) out << ",";
        out << "\n";
    }
    out << "}};\n\n";

    out << "std::string_view get(std::string_view lang) {\n";
    out << "    for (auto const &e : entries)\n";
    out << "        if (e.code == lang) return e.data;\n";
    out << "    return {};\n";
    out << "}\n\n";

    out << "std::vector<std::string_view> languages() {\n";
    out << "    std::vector<std::string_view> out;\n";
    out << "    out.reserve(entries.size());\n";
    out << "    for (auto const &e : entries) out.push_back(e.code);\n";
    out << "    return out;\n";
    out << "}\n\n";

    out << "} // namespace i18n::builtin\n";

    std::cout << "po2cpp: wrote " << output << " with " << langs.size()
              << " language(s)\n";
    return 0;
}
